#!/bin/sh

set +e
rm -rf tmp/redis
mkdir tmp
set -e

version=${REDIS_BRANCH:-3.0.3}
binaries="../../versions/$version/bin"

pushd tmp

git clone -b $version --single-branch --depth 1 https://github.com/antirez/redis.git

cd redis
make

mkdir -p $binaries

echo $(git rev-parse HEAD) > $binaries/.gitcommit
for file in src/redis-cli src/redis-server; do
  cp -f $file $binaries
done

popd
rm -rf tmp/redis
